//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratista
    {
        public int codigoC { get; set; }
        public string nombreCompleto { get; set; }
        public string domicilio { get; set; }
        public string contactos { get; set; }
        public string recomendaciones { get; set; }
    }
}
